tnts:
  big:
    radius: 50 # радиус взрыва
    fuse-ticks: 40 # задержка перед взрывом в тиках
    custom-name: '&aМощная бомба' # надпись над динамитом
    enable-custom-name: false # включение надписи
    item-name: '&aМощная бомба' # название динамита как предмета
    item-lore: # описание динамита как предмета
      - ''
      - '&FРадиус: &#ff0000{radius}'
      - '&fЗадержка: &6{fuse}'
  large:
    radius: 100 # радиус взрыва
    fuse-ticks: 100 # задержка перед взрывом в тиках
    custom-name: '&eВодородная бомба' # надпись над динамитом
    enable-custom-name: true # включение надписи
    item-name: '&eВодородная бомба' # название динамита как предмета
    item-lore: # описание динамита как предмета
      - ''
      - '&FРадиус: &d{radius}'
      - '&fЗадержка: &6{fuse}'