name: UpgradedTNT
version: '1.0'
main: plugin.ap.upgradedTNT.UpgradedTNT
api-version: '1.20'
load: STARTUP
commands:
  upgradedtnt:
    aliases: [ut, tnt, upgraded]
    permission: 'upgradedtnt.cmd'
    permission-message: 'У вас недостаточно прав!'
